//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace juego{
	public class bichicho: MonoBehaviour 
		{	
		private SpriteRenderer renderBicho;
		private tipo_bicho tipo;
		private int pv;
		private int vel;
				public bichicho ()
				{
						tipo = new tipo_bicho ();
						Pv = 100;
						vel = 100;
				}
				public int Pv {
						get{ return pv;}
						set{ pv = value;}
				}
				public int Vel {
						get{ return vel;}
						set{ vel = value;}
				}
	
		
		public IEnumerator Start () {
			renderBicho = gameObject.GetComponent<SpriteRenderer>();
			WWW www = new WWW(tipo.Sprites[0]);
			yield return www; 
			Sprite sprite = new Sprite();
			sprite = Sprite.Create(www.texture, new Rect(0, 0, 60, 60),new Vector2(0, 0),100.0f);
			
			renderBicho.sprite = sprite;
		}
		
		// Update is called once per frame
		void Update () {
			if (renderBicho.transform.position.y > -1.47) {
				renderBicho.transform.Translate (Vector3.right * Time.deltaTime * 2);
						} else {
				
				if (renderBicho.transform.position.y < -1.47) {
					renderBicho.transform.rotation = new Quaternion (0, 0, 0, 0);
								}
				renderBicho.transform.Translate (Vector3.up * Time.deltaTime * 2);
						}
			if (renderBicho.transform.position.x > 3) {
				Destroy (renderBicho.gameObject);
						}
				}
	}
}

