//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace juego{
	public class bichicho:MonoBehaviour
		{	
		public static Transform posicionBicho;
		private tipo_bicho tipo;
		private int pv;
		private int vel;

				public bichicho ()
				{
						tipo = new tipo_bicho ();
						Pv = 100;
						vel = 100;
				}
				public int Pv {
						get{ return pv;}
						set{ pv = value;}
				}
				public int Vel {
						get{ return vel;}
						set{ vel = value;}
				}
	
		
		public void Start () {

		}
		
		// Update is called once per frame
		void Update () {
			posicionBicho = transform;
			if (transform.position.y > -1.47) 		{
				transform.Translate (Vector3.right * Time.deltaTime * 2);
						} else {
				
				if (transform.position.y < -1.47) {
					transform.rotation = new Quaternion (0, 0, 0, 0);
								}
				transform.Translate (Vector3.up * Time.deltaTime * 2);
						}
			if (transform.position.x > 3) {
				Destroy (gameObject);
						}
				}
	}
}

