//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace juego{

		public class point
		{
		private float x;
		private float y;

		public point (float X, float Y)
		{
			x = X;
			y = Y;
		}

		public 	float X 
		{
			get { return x; }
			set { x = value; }
		}
		public 	float Y
		{
			get { return y; }
			set { Y= value; }
		}
	}
}

