//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace juego{
		public class spawn
		{
		private point inicio;
		private point final;
		private point[] recorrido;

				public spawn (float iniciox, float inicioy,float finalx, float finaly)
				{
					inicio = new point (iniciox, inicioy);		
					final = new point (finalx, finaly);
				}
				public 	point Inicio
				{
					get { return inicio; }
				}
				public 	point Final
				{
					get { return final; }
				}
				public point[] Recorrido {
			
						get { return recorrido; }
						set { recorrido = value; }
				}

		}
}

