//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace juego{
	public class tipo_bicho: MonoBehaviour 
		{
		private string[] sprites;
		private string[] sound;
		private int quimica;
				public tipo_bicho ()
				{
					sprites = new string[1];
					sprites[0] = "file://D:\\torretas\\Assets\\bicho.psd";
				}
				public string[] Sprites {
						get{ return sprites;}
				}
		}
}

