//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace juego{
	public class tipo_bicho
		{
		private float cd;
		private int quimica;
				public tipo_bicho ()
				{
					
				}
		public float Cd {
						get{ return cd;}
				}

		}
}

